version: "3.5"
services:
  client:
    build: ./client
    image: client
    container_name: client
    restart: always
    ports:
      - "9085:80"
    depends_on:
      - backend
    networks:
      - my-network

  backend:
    build: ./backend
    image: backend
    container_name: backend
    restart: always
    environment:
      - DB_CONN_STRING=${DB_CONN_STRING}
      - DB_NAME=${DB_NAME}
      - DB_PROFILES_COLLECTION_NAME=${DB_PROFILES_COLLECTION_NAME}
      - DB_USERS_COLLECTION_NAME=${DB_USERS_COLLECTION_NAME}
      - SERVICE_PORT=${SERVICE_PORT}
      - SERVICE_IP_ADDRESS=${SERVICE_IP_ADDRESS}
    ports:
      - "9084:8080"
    networks:
      - my-network
    volumes:
      - ./images:/app/src/images/

networks:
  my-network:
    driver: bridge
