services:
  client:
    build: ./client
    image: client
    container_name: client
    restart: always
    depends_on:
      - backend

  backend:
    build: ./backend
    image: backend
    container_name: backend
    restart: always
    environment:
      - DB_CONN_STRING=${DB_CONN_STRING}
      - DB_NAME=${DB_NAME}
      - DB_PROFILES_COLLECTION_NAME=${DB_PROFILES_COLLECTION_NAME}
      - DB_USERS_COLLECTION_NAME=${DB_USERS_COLLECTION_NAME}
      - SERVICE_PORT=${SERVICE_PORT}
      - SERVICE_IP_ADDRESS=${SERVICE_IP_ADDRESS}
    volumes:
      - ./images:/app/src/images/
