version: "3.5"

services:
  client:
    build: ./client
    image: client
    container_name: client
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - my-network

  backend:
    build: ./backend
    image: backend
    container_name: backend
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    networks:
      - my-network

  mongodb:
    image: mongo:latest
    container_name: database
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: todo
    volumes:
      - ./init-scripts:/docker-entrypoint-initdb.d
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
